import crypto from 'node:crypto';

export const AGENT_VERSION = '0.2.0';

export function nowISO() {
  return new Date().toISOString();
}

export function randomToken(bytes = 32) {
  return crypto.randomBytes(bytes).toString('base64url');
}

export function sha256(value) {
  return crypto.createHash('sha256').update(value).digest('hex');
}

export function safeEqual(a, b) {
  const left = Buffer.from(String(a));
  const right = Buffer.from(String(b));
  if (left.length !== right.length) return false;
  return crypto.timingSafeEqual(left, right);
}

export function parseBoolean(value, fallback = false) {
  if (value === undefined || value === null || value === '') return fallback;
  return ['1', 'true', 'yes', 'on'].includes(String(value).toLowerCase());
}

export function normalizeHost(value, { listen = false } = {}) {
  const host = String(value ?? '').trim();
  if (!host && listen) return '0.0.0.0';
  if (!host || host.length > 253 || /[\s\[\]'"`\\/]/.test(host)) {
    throw new Error('地址格式无效');
  }
  return host;
}

export function normalizePort(value) {
  const port = Number(value);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('端口必须是 1-65535 的整数');
  }
  return port;
}

export function validateRule(input) {
  const name = String(input.name ?? '').trim();
  if (!name || name.length > 80) throw new Error('规则名称长度必须为 1-80');
  return {
    name,
    nodeId: Number(input.nodeId),
    listenHost: normalizeHost(input.listenHost, { listen: true }),
    listenPort: normalizePort(input.listenPort),
    remoteHost: normalizeHost(input.remoteHost),
    remotePort: normalizePort(input.remotePort),
    enabled: input.enabled === false || input.enabled === 0 ? 0 : 1
  };
}

export function endpoint(host, port) {
  return host.includes(':') ? `[${host}]:${port}` : `${host}:${port}`;
}

export function renderRealmConfig(rules) {
  const lines = [
    '# Generated by Koyun Agent. Do not edit manually.',
    '[network]',
    'no_tcp = false',
    'use_udp = false',
    ''
  ];
  const listeners = new Set();
  for (const rule of rules.filter((item) => item.enabled !== false)) {
    const listenHost = normalizeHost(rule.listenHost, { listen: true });
    const remoteHost = normalizeHost(rule.remoteHost);
    const listenPort = normalizePort(rule.listenPort);
    const remotePort = normalizePort(rule.remotePort);
    const listener = endpoint(listenHost, listenPort);
    if (listeners.has(listener)) throw new Error(`监听地址重复：${listener}`);
    listeners.add(listener);
    lines.push('[[endpoints]]');
    lines.push(`listen = ${JSON.stringify(listener)}`);
    lines.push(`remote = ${JSON.stringify(endpoint(remoteHost, remotePort))}`);
    lines.push('');
  }
  return `${lines.join('\n')}\n`;
}

export function hashConfig(config) {
  return sha256(JSON.stringify(config));
}
